lang: en-US
title: Programming Dungeon
email: mycroft1891@gmail.com
description: 'Code like Good Wine, takes times'
image: /assets/img/main
baseurl: null
url: "https://mycroft1891.github.io"
google_analytics: UA-112012666-1
author:
  name: Alexander Luna
  twitter: mr_moon95
  picture: "https://pbs.twimg.com/profile_images/925100245146656768/KvQL2ei5_400x400.jpg"
twitter_username: mr_moon95
github_username: mycroft1891
logo: /favicon.svg
markdown: kramdown
remote_theme: mmistakes/jekyll-theme-basically-basic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-admin
feed:
  path: atom.xml
paginate: 10
paginate_path: '/page:num/'
exclude:
  - package.json
  - Gruntfile.js
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      read_time: true
